controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller\
    type: attribute
home:
    path: /
    controller: App\Controller\DefaultController::index

admin_dashboard:
    path: /admin
    controller: App\Controller\AdminController::index

coach_dashboard:
    path: /coach
    controller: App\Controller\CoachController::index

user_dashboard:
    path: /user
    controller: App\Controller\UserController::index
